// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diagrams.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDiagram = `-- name: CreateDiagram :one
INSERT INTO diagrams (id, page_id, xml)
VALUES ($1, $2, '')
RETURNING id, page_id, xml, updated_at
`

type CreateDiagramParams struct {
	ID     uuid.UUID `json:"id"`
	PageID *int64    `json:"page_id"`
}

type CreateDiagramRow struct {
	ID        uuid.UUID          `json:"id"`
	PageID    *int64             `json:"page_id"`
	Xml       string             `json:"xml"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDiagram(ctx context.Context, arg CreateDiagramParams) (CreateDiagramRow, error) {
	row := q.db.QueryRow(ctx, createDiagram, arg.ID, arg.PageID)
	var i CreateDiagramRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Xml,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiagram = `-- name: GetDiagram :one
SELECT id, page_id, xml, updated_at
FROM diagrams
WHERE id = $1
`

type GetDiagramRow struct {
	ID        uuid.UUID          `json:"id"`
	PageID    *int64             `json:"page_id"`
	Xml       string             `json:"xml"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDiagram(ctx context.Context, id uuid.UUID) (GetDiagramRow, error) {
	row := q.db.QueryRow(ctx, getDiagram, id)
	var i GetDiagramRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Xml,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiagramPreview = `-- name: GetDiagramPreview :one
SELECT preview
FROM diagrams
WHERE id = $1
`

func (q *Queries) GetDiagramPreview(ctx context.Context, id uuid.UUID) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDiagramPreview, id)
	var preview []byte
	err := row.Scan(&preview)
	return preview, err
}

const updateDiagram = `-- name: UpdateDiagram :exec
UPDATE diagrams
SET xml        = $2,
    preview    = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateDiagramParams struct {
	ID      uuid.UUID `json:"id"`
	Xml     string    `json:"xml"`
	Preview []byte    `json:"preview"`
}

func (q *Queries) UpdateDiagram(ctx context.Context, arg UpdateDiagramParams) error {
	_, err := q.db.Exec(ctx, updateDiagram, arg.ID, arg.Xml, arg.Preview)
	return err
}
