// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: favorites.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addFavorite = `-- name: AddFavorite :exec
INSERT INTO favorites (user_id, page_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddFavoriteParams struct {
	UserID int64 `json:"user_id"`
	PageID int64 `json:"page_id"`
}

func (q *Queries) AddFavorite(ctx context.Context, arg AddFavoriteParams) error {
	_, err := q.db.Exec(ctx, addFavorite, arg.UserID, arg.PageID)
	return err
}

const listFavorites = `-- name: ListFavorites :many
SELECT f.page_id, f.created_at, p.title, p.icon, p.project_id
FROM favorites f
JOIN pages p ON p.id = f.page_id
WHERE f.user_id = $1
  AND p.deleted_at IS NULL
  AND NOT p.is_template
ORDER BY f.created_at DESC, f.page_id
`

type ListFavoritesRow struct {
	PageID    int64              `json:"page_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	ProjectID int64              `json:"project_id"`
}

// Избранное пользователя с метаданными страниц; удалённые и шаблоны
// отфильтрованы, доступность проекта проверяет хендлер.
func (q *Queries) ListFavorites(ctx context.Context, userID int64) ([]ListFavoritesRow, error) {
	rows, err := q.db.Query(ctx, listFavorites, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFavoritesRow{}
	for rows.Next() {
		var i ListFavoritesRow
		if err := rows.Scan(
			&i.PageID,
			&i.CreatedAt,
			&i.Title,
			&i.Icon,
			&i.ProjectID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeFavorite = `-- name: RemoveFavorite :exec
DELETE FROM favorites
WHERE user_id = $1 AND page_id = $2
`

type RemoveFavoriteParams struct {
	UserID int64 `json:"user_id"`
	PageID int64 `json:"page_id"`
}

func (q *Queries) RemoveFavorite(ctx context.Context, arg RemoveFavoriteParams) error {
	_, err := q.db.Exec(ctx, removeFavorite, arg.UserID, arg.PageID)
	return err
}
