// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getFile = `-- name: GetFile :one
SELECT id, page_id, filename, mime, size, content, created_at
FROM files
WHERE id = $1
`

type GetFileRow struct {
	ID        uuid.UUID          `json:"id"`
	PageID    *int64             `json:"page_id"`
	Filename  string             `json:"filename"`
	Mime      string             `json:"mime"`
	Size      int64              `json:"size"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetFile(ctx context.Context, id uuid.UUID) (GetFileRow, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i GetFileRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Filename,
		&i.Mime,
		&i.Size,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertFile = `-- name: InsertFile :exec
INSERT INTO files (id, page_id, filename, mime, size, content)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertFileParams struct {
	ID       uuid.UUID `json:"id"`
	PageID   *int64    `json:"page_id"`
	Filename string    `json:"filename"`
	Mime     string    `json:"mime"`
	Size     int64     `json:"size"`
	Content  []byte    `json:"content"`
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) error {
	_, err := q.db.Exec(ctx, insertFile,
		arg.ID,
		arg.PageID,
		arg.Filename,
		arg.Mime,
		arg.Size,
		arg.Content,
	)
	return err
}
