// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addGroupMember = `-- name: AddGroupMember :exec
INSERT INTO group_members (group_id, user_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddGroupMemberParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) AddGroupMember(ctx context.Context, arg AddGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addGroupMember, arg.GroupID, arg.UserID)
	return err
}

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (name) VALUES ($1) RETURNING id, name, created_at, source
`

func (q *Queries) CreateGroup(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.Source,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = $1
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProjectGroupRole = `-- name: GetProjectGroupRole :one
SELECT pgm.role
FROM project_group_members pgm
JOIN group_members gm ON gm.group_id = pgm.group_id
WHERE pgm.project_id = $1 AND gm.user_id = $2
ORDER BY CASE pgm.role WHEN 'admin' THEN 3 WHEN 'editor' THEN 2 ELSE 1 END DESC
LIMIT 1
`

type GetProjectGroupRoleParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

// Лучшая роль пользователя в проекте через его группы.
func (q *Queries) GetProjectGroupRole(ctx context.Context, arg GetProjectGroupRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectGroupRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listGroupMembers = `-- name: ListGroupMembers :many
SELECT u.id, u.name, u.username, u.email
FROM group_members gm
JOIN users u ON u.id = gm.user_id
WHERE gm.group_id = $1
ORDER BY u.name, u.id
`

type ListGroupMembersRow struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Username string `json:"username"`
	Email    string `json:"email"`
}

func (q *Queries) ListGroupMembers(ctx context.Context, groupID int64) ([]ListGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupMembersRow{}
	for rows.Next() {
		var i ListGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT g.id, g.name, g.created_at, COUNT(gm.user_id) AS member_count
FROM groups g
LEFT JOIN group_members gm ON gm.group_id = g.id
GROUP BY g.id
ORDER BY g.name
`

type ListGroupsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListGroups(ctx context.Context) ([]ListGroupsRow, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGroupsRow{}
	for rows.Next() {
		var i ListGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectGroups = `-- name: ListProjectGroups :many
SELECT pgm.group_id, pgm.role, g.name
FROM project_group_members pgm
JOIN groups g ON g.id = pgm.group_id
WHERE pgm.project_id = $1
ORDER BY g.name
`

type ListProjectGroupsRow struct {
	GroupID int64  `json:"group_id"`
	Role    string `json:"role"`
	Name    string `json:"name"`
}

func (q *Queries) ListProjectGroups(ctx context.Context, projectID int64) ([]ListProjectGroupsRow, error) {
	rows, err := q.db.Query(ctx, listProjectGroups, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectGroupsRow{}
	for rows.Next() {
		var i ListProjectGroupsRow
		if err := rows.Scan(&i.GroupID, &i.Role, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneLDAPMemberships = `-- name: PruneLDAPMemberships :exec
DELETE FROM group_members gm
USING groups g
WHERE g.id = gm.group_id
  AND g.source = 'ldap'
  AND gm.user_id = $1
  AND g.id <> ALL($2::bigint[])
`

type PruneLDAPMembershipsParams struct {
	UserID  int64   `json:"user_id"`
	KeepIds []int64 `json:"keep_ids"`
}

// Убрать пользователя из ldap-зеркал, которых больше нет в его группах.
func (q *Queries) PruneLDAPMemberships(ctx context.Context, arg PruneLDAPMembershipsParams) error {
	_, err := q.db.Exec(ctx, pruneLDAPMemberships, arg.UserID, arg.KeepIds)
	return err
}

const removeGroupMember = `-- name: RemoveGroupMember :exec
DELETE FROM group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveGroupMemberParams struct {
	GroupID int64 `json:"group_id"`
	UserID  int64 `json:"user_id"`
}

func (q *Queries) RemoveGroupMember(ctx context.Context, arg RemoveGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeGroupMember, arg.GroupID, arg.UserID)
	return err
}

const removeProjectGroup = `-- name: RemoveProjectGroup :exec
DELETE FROM project_group_members WHERE project_id = $1 AND group_id = $2
`

type RemoveProjectGroupParams struct {
	ProjectID int64 `json:"project_id"`
	GroupID   int64 `json:"group_id"`
}

func (q *Queries) RemoveProjectGroup(ctx context.Context, arg RemoveProjectGroupParams) error {
	_, err := q.db.Exec(ctx, removeProjectGroup, arg.ProjectID, arg.GroupID)
	return err
}

const upsertLDAPGroup = `-- name: UpsertLDAPGroup :one
INSERT INTO groups (name, source) VALUES ($1, 'ldap')
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id
`

// Зеркало LDAP-группы; одноимённая локальная группа переиспользуется
// (source не перетирается).
func (q *Queries) UpsertLDAPGroup(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRow(ctx, upsertLDAPGroup, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertProjectGroup = `-- name: UpsertProjectGroup :exec
INSERT INTO project_group_members (project_id, group_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, group_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertProjectGroupParams struct {
	ProjectID int64  `json:"project_id"`
	GroupID   int64  `json:"group_id"`
	Role      string `json:"role"`
}

func (q *Queries) UpsertProjectGroup(ctx context.Context, arg UpsertProjectGroupParams) error {
	_, err := q.db.Exec(ctx, upsertProjectGroup, arg.ProjectID, arg.GroupID, arg.Role)
	return err
}
