// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Diagram struct {
	ID        uuid.UUID          `json:"id"`
	PageID    *int64             `json:"page_id"`
	Xml       string             `json:"xml"`
	Preview   []byte             `json:"preview"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type File struct {
	ID        uuid.UUID          `json:"id"`
	PageID    *int64             `json:"page_id"`
	Filename  string             `json:"filename"`
	Mime      string             `json:"mime"`
	Size      int64              `json:"size"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Content   []byte             `json:"content"`
}

type Page struct {
	ID           int64              `json:"id"`
	ParentID     *int64             `json:"parent_id"`
	Title        string             `json:"title"`
	Content      []byte             `json:"content"`
	ContentText  string             `json:"content_text"`
	Position     int32              `json:"position"`
	Version      int32              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Icon         string             `json:"icon"`
	SearchVector interface{}        `json:"search_vector"`
	CreatedBy    *int64             `json:"created_by"`
	UpdatedBy    *int64             `json:"updated_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type PageRevision struct {
	ID        int64              `json:"id"`
	PageID    int64              `json:"page_id"`
	Version   int32              `json:"version"`
	Title     string             `json:"title"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	AuthorID  *int64             `json:"author_id"`
}

type User struct {
	ID         int64              `json:"id"`
	Subject    string             `json:"subject"`
	Username   string             `json:"username"`
	Name       string             `json:"name"`
	Email      string             `json:"email"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}
