// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPage = `-- name: CreatePage :one
INSERT INTO pages (parent_id, title, position)
VALUES ($1, $2, COALESCE(
    (SELECT MAX(position) + 1 FROM pages WHERE parent_id IS NOT DISTINCT FROM $1),
    0
))
RETURNING id, parent_id, title, icon, content, position, version, created_at, updated_at
`

type CreatePageParams struct {
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
}

type CreatePageRow struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Content   []byte             `json:"content"`
	Position  int32              `json:"position"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage, arg.ParentID, arg.Title)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT id, parent_id, title, icon, content, position, version, created_at, updated_at
FROM pages
WHERE id = $1
`

type GetPageRow struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Content   []byte             `json:"content"`
	Position  int32              `json:"position"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPageTree = `-- name: GetPageTree :many
SELECT id, parent_id, title, icon, position
FROM pages
ORDER BY parent_id NULLS FIRST, position, id
`

type GetPageTreeRow struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	Position int32  `json:"position"`
}

// Плоский список для построения дерева в сайдбаре.
func (q *Queries) GetPageTree(ctx context.Context) ([]GetPageTreeRow, error) {
	rows, err := q.db.Query(ctx, getPageTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPageTreeRow{}
	for rows.Next() {
		var i GetPageTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Icon,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevision = `-- name: GetRevision :one
SELECT id, page_id, version, title, content, created_at
FROM page_revisions
WHERE id = $1
`

func (q *Queries) GetRevision(ctx context.Context, id int64) (PageRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, id)
	var i PageRevision
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertRevision = `-- name: InsertRevision :exec
INSERT INTO page_revisions (page_id, version, title, content)
VALUES ($1, $2, $3, $4)
`

type InsertRevisionParams struct {
	PageID  int64  `json:"page_id"`
	Version int32  `json:"version"`
	Title   string `json:"title"`
	Content []byte `json:"content"`
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.PageID,
		arg.Version,
		arg.Title,
		arg.Content,
	)
	return err
}

const latestRevisionAt = `-- name: LatestRevisionAt :one
SELECT MAX(created_at)::timestamptz AS last_at
FROM page_revisions
WHERE page_id = $1
`

func (q *Queries) LatestRevisionAt(ctx context.Context, pageID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestRevisionAt, pageID)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}

const listRevisions = `-- name: ListRevisions :many
SELECT id, page_id, version, title, created_at
FROM page_revisions
WHERE page_id = $1
ORDER BY version DESC
LIMIT 100
`

type ListRevisionsRow struct {
	ID        int64              `json:"id"`
	PageID    int64              `json:"page_id"`
	Version   int32              `json:"version"`
	Title     string             `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListRevisions(ctx context.Context, pageID int64) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevisionsRow{}
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Version,
			&i.Title,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePage = `-- name: MovePage :exec
UPDATE pages
SET parent_id  = $2,
    position   = $3,
    updated_at = now()
WHERE id = $1
`

type MovePageParams struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Position int32  `json:"position"`
}

func (q *Queries) MovePage(ctx context.Context, arg MovePageParams) error {
	_, err := q.db.Exec(ctx, movePage, arg.ID, arg.ParentID, arg.Position)
	return err
}

const searchPages = `-- name: SearchPages :many
SELECT id, parent_id, title, icon,
       ts_headline('simple', content_text, plainto_tsquery('simple', $1),
                   'MaxFragments=1,MaxWords=20,MinWords=5') AS snippet
FROM pages
WHERE to_tsvector('simple', title || ' ' || content_text) @@ plainto_tsquery('simple', $1)
ORDER BY ts_rank(to_tsvector('simple', content_text), plainto_tsquery('simple', $1)) DESC
LIMIT 50
`

type SearchPagesRow struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	Snippet  []byte `json:"snippet"`
}

func (q *Queries) SearchPages(ctx context.Context, plaintoTsquery string) ([]SearchPagesRow, error) {
	rows, err := q.db.Query(ctx, searchPages, plaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPagesRow{}
	for rows.Next() {
		var i SearchPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Icon,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title        = $2,
    content      = $3,
    content_text = $4,
    icon         = $6,
    version      = version + 1,
    updated_at   = now()
WHERE id = $1
  AND version = $5
RETURNING id, parent_id, title, icon, content, position, version, created_at, updated_at
`

type UpdatePageParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Content     []byte `json:"content"`
	ContentText string `json:"content_text"`
	Version     int32  `json:"version"`
	Icon        string `json:"icon"`
}

type UpdatePageRow struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Content   []byte             `json:"content"`
	Position  int32              `json:"position"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Optimistic lock: обновит строку только если version совпадает.
// Если вернулось 0 строк — конфликт версий (кто-то успел сохранить).
func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (UpdatePageRow, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.ContentText,
		arg.Version,
		arg.Icon,
	)
	var i UpdatePageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
