// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pages.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSiblings = `-- name: CountSiblings :one

SELECT COUNT(*)
FROM pages
WHERE parent_id IS NOT DISTINCT FROM $1
  AND id <> $2
`

type CountSiblingsParams struct {
	ParentID *int64 `json:"parent_id"`
	PageID   int64  `json:"page_id"`
}

// Проверка «candidate в поддереве root» для move живёт сырым SQL в
// internal/pages/handler.go (isInSubtreeSQL): рекурсивный CTE не проходит
// через анализатор sqlc.
// Число детей родителя без самой переносимой страницы (для клампа позиции).
func (q *Queries) CountSiblings(ctx context.Context, arg CountSiblingsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSiblings, arg.ParentID, arg.PageID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPage = `-- name: CreatePage :one
INSERT INTO pages (parent_id, title, position, created_by, updated_by)
VALUES ($1, $2, COALESCE(
    (SELECT MAX(position) + 1 FROM pages WHERE parent_id IS NOT DISTINCT FROM $1),
    0
), $3, $3)
RETURNING id, parent_id, title, icon, content, position, version, created_at, updated_at
`

type CreatePageParams struct {
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
	AuthorID *int64 `json:"author_id"`
}

type CreatePageRow struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Content   []byte             `json:"content"`
	Position  int32              `json:"position"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePage(ctx context.Context, arg CreatePageParams) (CreatePageRow, error) {
	row := q.db.QueryRow(ctx, createPage, arg.ParentID, arg.Title, arg.AuthorID)
	var i CreatePageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePage = `-- name: DeletePage :exec
DELETE FROM pages WHERE id = $1
`

func (q *Queries) DeletePage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePage, id)
	return err
}

const getPage = `-- name: GetPage :one
SELECT p.id, p.parent_id, p.title, p.icon, p.content, p.position, p.version,
       p.created_at, p.updated_at,
       u.name AS updated_by_name
FROM pages p
LEFT JOIN users u ON u.id = p.updated_by
WHERE p.id = $1
`

type GetPageRow struct {
	ID            int64              `json:"id"`
	ParentID      *int64             `json:"parent_id"`
	Title         string             `json:"title"`
	Icon          string             `json:"icon"`
	Content       []byte             `json:"content"`
	Position      int32              `json:"position"`
	Version       int32              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	UpdatedByName *string            `json:"updated_by_name"`
}

func (q *Queries) GetPage(ctx context.Context, id int64) (GetPageRow, error) {
	row := q.db.QueryRow(ctx, getPage, id)
	var i GetPageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedByName,
	)
	return i, err
}

const getPageMeta = `-- name: GetPageMeta :one
SELECT id, parent_id, position
FROM pages
WHERE id = $1
`

type GetPageMetaRow struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Position int32  `json:"position"`
}

// Лёгкое чтение для move: родитель и позиция без контента.
func (q *Queries) GetPageMeta(ctx context.Context, id int64) (GetPageMetaRow, error) {
	row := q.db.QueryRow(ctx, getPageMeta, id)
	var i GetPageMetaRow
	err := row.Scan(&i.ID, &i.ParentID, &i.Position)
	return i, err
}

const getPageTree = `-- name: GetPageTree :many
SELECT id, parent_id, title, icon, position
FROM pages
ORDER BY parent_id NULLS FIRST, position, id
`

type GetPageTreeRow struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	Position int32  `json:"position"`
}

// Плоский список для построения дерева в сайдбаре.
func (q *Queries) GetPageTree(ctx context.Context) ([]GetPageTreeRow, error) {
	rows, err := q.db.Query(ctx, getPageTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPageTreeRow{}
	for rows.Next() {
		var i GetPageTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Icon,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevision = `-- name: GetRevision :one
SELECT id, page_id, version, title, content, created_at
FROM page_revisions
WHERE id = $1
`

type GetRevisionRow struct {
	ID        int64              `json:"id"`
	PageID    int64              `json:"page_id"`
	Version   int32              `json:"version"`
	Title     string             `json:"title"`
	Content   []byte             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetRevision(ctx context.Context, id int64) (GetRevisionRow, error) {
	row := q.db.QueryRow(ctx, getRevision, id)
	var i GetRevisionRow
	err := row.Scan(
		&i.ID,
		&i.PageID,
		&i.Version,
		&i.Title,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const insertRevision = `-- name: InsertRevision :exec
INSERT INTO page_revisions (page_id, version, title, content, author_id)
VALUES ($1, $2, $3, $4, $5)
`

type InsertRevisionParams struct {
	PageID   int64  `json:"page_id"`
	Version  int32  `json:"version"`
	Title    string `json:"title"`
	Content  []byte `json:"content"`
	AuthorID *int64 `json:"author_id"`
}

func (q *Queries) InsertRevision(ctx context.Context, arg InsertRevisionParams) error {
	_, err := q.db.Exec(ctx, insertRevision,
		arg.PageID,
		arg.Version,
		arg.Title,
		arg.Content,
		arg.AuthorID,
	)
	return err
}

const latestRevisionAt = `-- name: LatestRevisionAt :one
SELECT MAX(created_at)::timestamptz AS last_at
FROM page_revisions
WHERE page_id = $1
`

func (q *Queries) LatestRevisionAt(ctx context.Context, pageID int64) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestRevisionAt, pageID)
	var last_at pgtype.Timestamptz
	err := row.Scan(&last_at)
	return last_at, err
}

const listRevisions = `-- name: ListRevisions :many
SELECT r.id, r.page_id, r.version, r.title, r.created_at,
       u.name AS author_name
FROM page_revisions r
LEFT JOIN users u ON u.id = r.author_id
WHERE r.page_id = $1
ORDER BY r.version DESC
LIMIT 100
`

type ListRevisionsRow struct {
	ID         int64              `json:"id"`
	PageID     int64              `json:"page_id"`
	Version    int32              `json:"version"`
	Title      string             `json:"title"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	AuthorName *string            `json:"author_name"`
}

func (q *Queries) ListRevisions(ctx context.Context, pageID int64) ([]ListRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listRevisions, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRevisionsRow{}
	for rows.Next() {
		var i ListRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.PageID,
			&i.Version,
			&i.Title,
			&i.CreatedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const movePage = `-- name: MovePage :exec
UPDATE pages
SET parent_id  = $2,
    position   = $3,
    updated_at = now()
WHERE id = $1
`

type MovePageParams struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Position int32  `json:"position"`
}

func (q *Queries) MovePage(ctx context.Context, arg MovePageParams) error {
	_, err := q.db.Exec(ctx, movePage, arg.ID, arg.ParentID, arg.Position)
	return err
}

const searchPages = `-- name: SearchPages :many
SELECT id, parent_id, title, icon,
       ts_headline('russian', content_text, plainto_tsquery('russian', $1),
                   'MaxFragments=1,MaxWords=20,MinWords=5') AS snippet
FROM pages
WHERE search_vector @@ plainto_tsquery('russian', $1)
ORDER BY ts_rank(search_vector, plainto_tsquery('russian', $1)) DESC
LIMIT 50
`

type SearchPagesRow struct {
	ID       int64  `json:"id"`
	ParentID *int64 `json:"parent_id"`
	Title    string `json:"title"`
	Icon     string `json:"icon"`
	Snippet  []byte `json:"snippet"`
}

// Поиск по генерируемой колонке search_vector (русская морфология, GIN-индекс).
func (q *Queries) SearchPages(ctx context.Context, plaintoTsquery string) ([]SearchPagesRow, error) {
	rows, err := q.db.Query(ctx, searchPages, plaintoTsquery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchPagesRow{}
	for rows.Next() {
		var i SearchPagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Title,
			&i.Icon,
			&i.Snippet,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shiftAfterRemove = `-- name: ShiftAfterRemove :exec
UPDATE pages
SET position = position - 1
WHERE parent_id IS NOT DISTINCT FROM $1
  AND position > $2
  AND id <> $3
`

type ShiftAfterRemoveParams struct {
	ParentID *int64 `json:"parent_id"`
	Position int32  `json:"position"`
	PageID   int64  `json:"page_id"`
}

// «Изъятие» страницы из старого родителя: соседи ниже сдвигаются вверх.
func (q *Queries) ShiftAfterRemove(ctx context.Context, arg ShiftAfterRemoveParams) error {
	_, err := q.db.Exec(ctx, shiftAfterRemove, arg.ParentID, arg.Position, arg.PageID)
	return err
}

const shiftForInsert = `-- name: ShiftForInsert :exec
UPDATE pages
SET position = position + 1
WHERE parent_id IS NOT DISTINCT FROM $1
  AND position >= $2
  AND id <> $3
`

type ShiftForInsertParams struct {
	ParentID *int64 `json:"parent_id"`
	Position int32  `json:"position"`
	PageID   int64  `json:"page_id"`
}

// Освобождение места под вставку: соседи с позиции вставки сдвигаются вниз.
func (q *Queries) ShiftForInsert(ctx context.Context, arg ShiftForInsertParams) error {
	_, err := q.db.Exec(ctx, shiftForInsert, arg.ParentID, arg.Position, arg.PageID)
	return err
}

const updatePage = `-- name: UpdatePage :one
UPDATE pages
SET title        = $2,
    content      = $3,
    content_text = $4,
    icon         = $6,
    updated_by   = $7,
    version      = version + 1,
    updated_at   = now()
WHERE id = $1
  AND version = $5
RETURNING id, parent_id, title, icon, content, position, version, created_at, updated_at
`

type UpdatePageParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Content     []byte `json:"content"`
	ContentText string `json:"content_text"`
	Version     int32  `json:"version"`
	Icon        string `json:"icon"`
	AuthorID    *int64 `json:"author_id"`
}

type UpdatePageRow struct {
	ID        int64              `json:"id"`
	ParentID  *int64             `json:"parent_id"`
	Title     string             `json:"title"`
	Icon      string             `json:"icon"`
	Content   []byte             `json:"content"`
	Position  int32              `json:"position"`
	Version   int32              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Optimistic lock: обновит строку только если version совпадает.
// Если вернулось 0 строк — конфликт версий (кто-то успел сохранить).
func (q *Queries) UpdatePage(ctx context.Context, arg UpdatePageParams) (UpdatePageRow, error) {
	row := q.db.QueryRow(ctx, updatePage,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.ContentText,
		arg.Version,
		arg.Icon,
		arg.AuthorID,
	)
	var i UpdatePageRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Title,
		&i.Icon,
		&i.Content,
		&i.Position,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
