// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countProjectPages = `-- name: CountProjectPages :one
SELECT COUNT(*) FROM pages WHERE project_id = $1
`

func (q *Queries) CountProjectPages(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectPages, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (key, name, icon, visibility)
VALUES ($1, $2, $3, $4)
RETURNING id, key, name, icon, created_at, visibility
`

type CreateProjectParams struct {
	Key        string `json:"key"`
	Name       string `json:"name"`
	Icon       string `json:"icon"`
	Visibility string `json:"visibility"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.Key,
		arg.Name,
		arg.Icon,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.Visibility,
	)
	return i, err
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects WHERE id = $1 AND key <> 'main'
`

// Дефолтный проект 'main' удалить нельзя; страницы держит FK RESTRICT.
func (q *Queries) DeleteProject(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProject, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPageProject = `-- name: GetPageProject :one
SELECT project_id FROM pages WHERE id = $1
`

// Проект страницы (включая корзину — гарды нужны и для restore/purge).
func (q *Queries) GetPageProject(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getPageProject, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const getProject = `-- name: GetProject :one
SELECT id, key, name, icon, created_at, visibility
FROM projects
WHERE id = $1
`

func (q *Queries) GetProject(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProject, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.Visibility,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, icon, created_at, visibility
FROM projects
WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.Visibility,
	)
	return i, err
}

const getProjectMemberRole = `-- name: GetProjectMemberRole :one
SELECT role FROM project_members WHERE project_id = $1 AND user_id = $2
`

type GetProjectMemberRoleParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) GetProjectMemberRole(ctx context.Context, arg GetProjectMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getProjectMemberRole, arg.ProjectID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT m.user_id, m.role, m.added_at, u.name, u.username, u.email
FROM project_members m
JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1
ORDER BY u.name, u.id
`

type ListProjectMembersRow struct {
	UserID   int64              `json:"user_id"`
	Role     string             `json:"role"`
	AddedAt  pgtype.Timestamptz `json:"added_at"`
	Name     string             `json:"name"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.AddedAt,
			&i.Name,
			&i.Username,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, key, name, icon, created_at, visibility
FROM projects
ORDER BY id
`

func (q *Queries) ListProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Project{}
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Name,
			&i.Icon,
			&i.CreatedAt,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeProjectMember = `-- name: RemoveProjectMember :exec
DELETE FROM project_members WHERE project_id = $1 AND user_id = $2
`

type RemoveProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) RemoveProjectMember(ctx context.Context, arg RemoveProjectMemberParams) error {
	_, err := q.db.Exec(ctx, removeProjectMember, arg.ProjectID, arg.UserID)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects
SET name = $2, icon = $3, visibility = $4
WHERE id = $1
RETURNING id, key, name, icon, created_at, visibility
`

type UpdateProjectParams struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Icon       string `json:"icon"`
	Visibility string `json:"visibility"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.ID,
		arg.Name,
		arg.Icon,
		arg.Visibility,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Icon,
		&i.CreatedAt,
		&i.Visibility,
	)
	return i, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :exec
INSERT INTO project_members (project_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, user_id) DO UPDATE SET role = EXCLUDED.role
`

type UpsertProjectMemberParams struct {
	ProjectID int64  `json:"project_id"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) error {
	_, err := q.db.Exec(ctx, upsertProjectMember, arg.ProjectID, arg.UserID, arg.Role)
	return err
}
