// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (subject, username, name, email)
VALUES ($1, $2, $3, $4)
ON CONFLICT (subject) DO UPDATE
SET username     = EXCLUDED.username,
    name         = EXCLUDED.name,
    email        = EXCLUDED.email,
    last_seen_at = now()
RETURNING id, subject, username, name, email, created_at, last_seen_at
`

type UpsertUserParams struct {
	Subject  string `json:"subject"`
	Username string `json:"username"`
	Name     string `json:"name"`
	Email    string `json:"email"`
}

// Регистрирует/обновляет пользователя по subject из JWT (или "dev").
// Вызывается из auth-middleware (с кэшем, не на каждый запрос).
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.Subject,
		arg.Username,
		arg.Name,
		arg.Email,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Username,
		&i.Name,
		&i.Email,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
